language: java

jdk:
  - openjdk8
  - openjdk11

matrix:
  fast_finish: true
  allow_failures:
    - jdk: openjdk11

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
